[options]
RootDir = /home/app
DBPath = /home/app/data/pacman-local
CacheDir = /home/app/data/pacman-local-cache
LogFile = /home/app/data/pacman.log

Include = /home/app/data/pacman-local.conf.d/*.conf