#!/usr/bin/env bash
# Rebuilds the fixture package used by LibAlpmSharp.Test and the RepoHost end to end tests.
#
# The package is assembled by hand rather than with makepkg so that it stays a few hundred bytes
# and so that every field the packages API reads is present and has a distinctive value. Run it
# from this directory; it overwrites the .pkg.tar.zst next to it.
set -euo pipefail

pkgname=pacmanmanager-test
pkgver=1.2.3-4
arch=x86_64
outfile="${pkgname}-${pkgver}-${arch}.pkg.tar.zst"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

mkdir -p "$workdir/usr/share/doc/$pkgname"
printf 'PacmanManager test fixture package.\n' > "$workdir/usr/share/doc/$pkgname/README"

cat > "$workdir/.PKGINFO" <<'PKGINFO'
# Generated by test-fixtures/packages/build-fixture.sh
pkgname = pacmanmanager-test
pkgbase = pacmanmanager-test
pkgver = 1.2.3-4
pkgdesc = Fixture package used by PacmanManager tests
url = https://github.com/PaulTrampert/PacmanManager
builddate = 1757116800
packager = Paul Trampert <paul.trampert@gmail.com>
size = 35
arch = x86_64
license = MIT
group = pacmanmanager
depend = glibc
optdepend = git: for the sync command
makedepend = cmake
checkdepend = python
provides = pacmanmanager-fixture
conflict = pacmanmanager-test-old
replaces = pacmanmanager-test-legacy
PKGINFO

# --mtime, --uid and --gid keep the archive byte for byte reproducible; without them the tar
# headers would carry the build machine's clock and user.
bsdtar --format=gnutar -C "$workdir" \
    --mtime "@1757116800" --uid 0 --gid 0 --uname root --gname root \
    -cf - .PKGINFO usr | zstd -19 -q -o "$outfile"
pacman -Qip "$outfile"
