#!/usr/bin/env bash
# Rebuilds the fixture packages used by LibAlpmSharp.Test and the RepoHost end to end tests.
#
# The packages are assembled by hand rather than with makepkg so that they stay a few hundred bytes
# and so that every field the packages API reads is present and has a distinctive value. Two
# versions of the same package are built: publishing refuses an upload that does not move the
# version forward, so testing a replacement takes a second, newer file. Run it from this directory;
# it overwrites the .pkg.tar.zst files next to it.
set -euo pipefail

pkgname=pacmanmanager-test
arch=x86_64
builddate=1757116800

# Builds one version of the fixture package. The metadata is identical apart from pkgver, so that a
# test replacing one with the other is exercising the version and nothing else.
build_fixture() {
    local pkgver="$1"
    local outfile="${pkgname}-${pkgver}-${arch}.pkg.tar.zst"

    local workdir
    workdir="$(mktemp -d)"
    trap 'rm -rf "$workdir"' RETURN

    mkdir -p "$workdir/usr/share/doc/$pkgname"
    printf 'PacmanManager test fixture package.\n' > "$workdir/usr/share/doc/$pkgname/README"

    cat > "$workdir/.PKGINFO" <<PKGINFO
# Generated by test-fixtures/packages/build-fixture.sh
pkgname = ${pkgname}
pkgbase = ${pkgname}
pkgver = ${pkgver}
pkgdesc = Fixture package used by PacmanManager tests
url = https://github.com/PaulTrampert/PacmanManager
builddate = ${builddate}
packager = Paul Trampert <paul.trampert@gmail.com>
size = 35
arch = ${arch}
license = MIT
group = pacmanmanager
depend = glibc
optdepend = git: for the sync command
makedepend = cmake
checkdepend = python
provides = pacmanmanager-fixture
conflict = pacmanmanager-test-old
replaces = pacmanmanager-test-legacy
PKGINFO

    # --mtime, --uid and --gid keep the archive byte for byte reproducible; without them the tar
    # headers would carry the build machine's clock and user.
    bsdtar --format=gnutar -C "$workdir" \
        --mtime "@${builddate}" --uid 0 --gid 0 --uname root --gname root \
        -cf - .PKGINFO usr | zstd -19 -q -f -o "$outfile"
    pacman -Qip "$outfile"
}

# The package every test that reads metadata loads.
build_fixture 1.2.3-4

# The upgrade: the same package one pkgver on, which is what a publish over the first one has to be.
build_fixture 1.2.4-1
