using PacmanManager.RepoHost.Exceptions;
using PacmanManager.RepoHost.Models;

namespace PacmanManager.RepoHost.Services;

/// <summary>
/// Mints, lists and revokes the current actor's own access tokens.
/// </summary>
/// <remarks>
/// <para>
/// Actor-scoped, like every other service: each method's subject is the tokens of the user supplied
/// by <see cref="IActorAccessor"/>, and no method takes a user argument, so a caller can never name
/// another user's token. Another user's token is reported as missing rather than forbidden.
/// </para>
/// <para>
/// Verifying a token is not here. It runs before an actor exists, so it lives on
/// <see cref="IUserService.GetUserByAccessTokenAsync"/>.
/// </para>
/// </remarks>
public interface IAccessTokenService
{
    /// <summary>
    /// Retrieves a page of the current actor's own tokens. No secret is ever returned.
    /// </summary>
    /// <param name="paginationParams">The pagination parameters.</param>
    /// <param name="filter">Caller-supplied criteria, which can only narrow the actor's own tokens.</param>
    /// <param name="sort">The order to return results in. Defaults to newest first.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the task to complete.</param>
    /// <returns>A page of the actor's tokens.</returns>
    /// <exception cref="NoCurrentUserException">Thrown when there is no user whose tokens to list.</exception>
    Task<PaginatedResponse<AccessToken>> GetAccessTokensAsync(
        PaginationParams paginationParams,
        AccessTokenFilter? filter = null,
        SortOptions<AccessTokenSortField>? sort = null,
        CancellationToken ct = default);

    /// <summary>
    /// Mints a token for the current actor's user.
    /// </summary>
    /// <remarks>
    /// The secret is 32 bytes from a CSPRNG, generated by
    /// <see cref="Authentication.AccessTokenFormat.GenerateSecret"/>, and only its fast, unsalted
    /// SHA-256 is stored. That hash is correct only because the secret is generated here: a value a
    /// user chose must never be accepted in its place.
    /// </remarks>
    /// <param name="request">The token's name and optional expiry.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the task to complete.</param>
    /// <returns>The minted token, carrying its secret. This is the only time the secret is returned.</returns>
    /// <exception cref="NoCurrentUserException">Thrown when there is no user to own the token.</exception>
    /// <exception cref="ItemExistsException">Thrown when the user already has a token of that name, compared without regard to case.</exception>
    Task<CreatedAccessToken> CreateAccessTokenAsync(CreateAccessTokenRequest request, CancellationToken ct = default);

    /// <summary>
    /// Revokes one of the current actor's own tokens by deleting it.
    /// </summary>
    /// <param name="tokenId">The id of the token to delete.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the task to complete.</param>
    /// <returns>
    /// <c>true</c> if the token was deleted; <c>false</c> if the actor has no token with that id,
    /// which includes a token that belongs to somebody else.
    /// </returns>
    /// <exception cref="NoCurrentUserException">Thrown when there is no user whose token to delete.</exception>
    Task<bool> DeleteAccessTokenAsync(Guid tokenId, CancellationToken ct = default);
}
