using PacmanManager.Entities;

namespace PacmanManager.RepoHost.Services;

/// <summary>
/// Provides services for managing users and their identity links.
/// </summary>
public interface IUserService
{
    /// <summary>
    /// Retrieves a user by their external identity provider identifiers.
    /// </summary>
    /// <param name="authority">The identity provider authority.</param>
    /// <param name="subject">The subject identifier from the identity provider.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the task to complete.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains the <see cref="User"/> if found; otherwise, <c>null</c>.</returns>
    Task<User?> GetUserByExternalIdAsync(string authority, string subject, CancellationToken ct = default);

    /// <summary>
    /// Retrieves a user by their email address.
    /// </summary>
    /// <param name="email">The email address of the user.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the task to complete.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains the <see cref="User"/> if found; otherwise, <c>null</c>.</returns>
    Task<User?> GetUserByEmailAsync(string email, CancellationToken ct = default);

    /// <summary>
    /// Creates a new user in the system.
    /// </summary>
    /// <param name="user">The user entity to create.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the task to complete.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains the created <see cref="User"/>.</returns>
    Task<User> CreateUserAsync(User user, CancellationToken ct = default);

    /// <summary>
    /// Links an existing user to an external identity provider.
    /// </summary>
    /// <param name="user">The user to link.</param>
    /// <param name="authority">The identity provider authority.</param>
    /// <param name="subject">The subject identifier from the identity provider.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the task to complete.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains the updated <see cref="User"/>.</returns>
    Task<User> LinkToIdentityAsync(
        User user, 
        string authority, 
        string subject,
        CancellationToken ct = default);

    /// <summary>
    /// Ensures that a user exists and is linked to the provided identity information. 
    /// If the user does not exist, one will be created.
    /// </summary>
    /// <param name="email">The email address of the user.</param>
    /// <param name="displayName">The display name for the user.</param>
    /// <param name="authority">The identity provider authority.</param>
    /// <param name="subject">The subject identifier from the identity provider.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the task to complete.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains the <see cref="User"/>.</returns>
    Task<User> EnsureUserLinkedAsync(string email, string displayName, string authority, string subject, CancellationToken ct = default);

    /// <summary>
    /// Returns the user the access token belongs to if and only if the token is valid; otherwise
    /// <c>null</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is a pre-authentication lookup: its result is what an authenticated principal is built
    /// from, so it runs before any <see cref="Authentication.Actor"/> exists and takes none.
    /// </para>
    /// <para>
    /// The fields are parsed with <see cref="Authentication.AccessTokenFormat"/>. A malformed
    /// username or password, an unknown token identifier, a secret that does not match, and an
    /// expired token all return <c>null</c>; none of them throws. A well-formed pair is verified in
    /// a single query predicated on both the identifier and the hash of the secret, so an unknown
    /// identifier and a wrong secret are the same outcome, reached by the same path.
    /// </para>
    /// <para>
    /// The fast, unsalted hash this relies on is correct only because a secret is 256 bits from a
    /// CSPRNG, generated by <see cref="Authentication.AccessTokenFormat.GenerateSecret"/>. It must
    /// never be used to verify a value a user chose.
    /// </para>
    /// <para>
    /// Every verification is logged with the token identifier, where the username yielded one, and
    /// every failure with its reason. The secret is never logged.
    /// </para>
    /// </remarks>
    /// <param name="username">The presented Basic username, <c>pmt_{tokenId:N}</c>.</param>
    /// <param name="password">The presented Basic password, <c>pms_{secret}</c>.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the task to complete.</param>
    /// <returns>A task whose result is the token's owner, or <c>null</c> if the credential does not verify.</returns>
    Task<User?> GetUserByAccessTokenAsync(string username, string password, CancellationToken ct = default);
}